<?php

namespace App\Http\Controllers\Api;

use App\Exports\PagesExport;
use App\Http\Controllers\Controller;
use App\Models\Site;
use App\Models\SiteAudit;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class ReportController extends Controller
{
    /**
     * Download PDF Audit Report
     */
    public function downloadPdf(Request $request, $siteId)
    {
        $site = $request->user()->sites()->findOrFail($siteId);
        
        // Get the latest summary data
        $summary = $site->on_page_summary;
        
        if (!$summary) {
            return response()->json(['success' => false, 'message' => 'No audit data found to generate report'], 404);
        }

        $settings = [
            'company_name'  => \App\Models\Setting::get('company_name', 'SEO Platform'),
            'primary_color' => \App\Models\Setting::get('primary_color', '#3b82f6'),
            'report_footer' => \App\Models\Setting::get('report_footer', 'Generated by SEO Platform'),
            'logo_url'      => \App\Models\Setting::get('logo_path')
                                ? \Illuminate\Support\Facades\Storage::disk('public')->url(\App\Models\Setting::get('logo_path'))
                                : null,
        ];

        $data = [
            'site'     => $site,
            'summary'  => $summary,
            'date'     => now()->format('F j, Y'),
            'settings' => $settings,
        ];

        $pdf = Pdf::loadView('reports.audit_summary', $data);
        
        return $pdf->download("seo-report-{$site->domain}.pdf");
    }

    /**
     * Download CSV export of all pages
     */
    public function downloadCsv(Request $request, $siteId)
    {
        $site = $request->user()->sites()->findOrFail($siteId);
        
        return Excel::download(new PagesExport($site->id), "seo-pages-{$site->domain}.csv");
    }
}
