<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Setting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class SettingsController extends Controller
{
    /**
     * Get all branding settings.
     */
    public function index()
    {
        return response()->json([
            'success' => true,
            'settings' => [
                'company_name'    => Setting::get('company_name', 'SEO Platform'),
                'primary_color'   => Setting::get('primary_color', '#3b82f6'),
                'logo_url'        => Setting::get('logo_path')
                                        ? Storage::disk('public')->url(Setting::get('logo_path'))
                                        : null,
                'report_footer'   => Setting::get('report_footer', 'Generated by SEO Platform'),
            ],
        ]);
    }

    /**
     * Update branding text settings.
     */
    public function update(Request $request)
    {
        $validated = $request->validate([
            'company_name'  => 'sometimes|string|max:100',
            'primary_color' => 'sometimes|string|max:20',
            'report_footer' => 'sometimes|string|max:200',
        ]);

        foreach ($validated as $key => $value) {
            Setting::set($key, $value);
        }

        return response()->json(['success' => true, 'message' => 'Settings saved.']);
    }

    /**
     * Upload a logo.
     */
    public function uploadLogo(Request $request)
    {
        $request->validate([
            'logo' => 'required|image|mimes:png,jpg,svg,webp|max:2048',
        ]);

        // Delete old logo
        $old = Setting::get('logo_path');
        if ($old && Storage::disk('public')->exists($old)) {
            Storage::disk('public')->delete($old);
        }

        $path = $request->file('logo')->store('branding', 'public');
        Setting::set('logo_path', $path);

        return response()->json([
            'success'  => true,
            'logo_url' => Storage::disk('public')->url($path),
        ]);
    }
}
